#!/bin/sh

wait_for_uci_wireless() {
	local timeout=30
	local elapsed=0
	local uci_detect
	local min_phy

	uci_detect=$(uci show wireless |grep wifi-device | wc -l)
	min_phy=$(ls /sys/kernel/debug/ath12k/ |wc -l)
	while [ "$uci_detect" -lt "$min_phy" ] && [ $elapsed -lt $timeout ]; do
		min_phy=$(ls /sys/kernel/debug/ath12k/ |wc -l)
		uci_detect=$(uci show wireless |grep wifi-device | wc -l)
		elapsed=$((elapsed + 1))
		sleep 1
	done
}

init_vendor_uci_wireless() {
	uci get wireless.vendor 1>/dev/null 2>/dev/null || {
		uci set wireless.vendor=vendor
	}
	min_phy=$(ls /sys/kernel/debug/ath12k/ |wc -l)
	uci  set wireless.vendor.min_phy=$min_phy
	uci  set wireless.vendor.phy_detect_timeout=20
	uci commit wireless
}

wait_for_uci_wireless
init_vendor_uci_wireless

exit 0

