include $(TOPDIR)/rules.mk
include $(INCLUDE_DIR)/kernel.mk

PKG_NAME:=qca-nss-eip
PKG_SOURCE_PROTO:=git
PKG_BRANCH:=win.nss.1.0.r37
PKG_RELEASE:=1
PKG_LICENSE:=ISC
PKG_SOURCE_URL:=https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-eip
PKG_MIRROR_HASH:=560779382bc58e38b5de72773f1877dcc2937c3cd6428c9fd164f6761c70ac27
PKG_VERSION:=6eece09cb90125188cef744d0b7fe88199d064ab

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
PKG_SOURCE_VERSION:=$(PKG_VERSION)


include $(INCLUDE_DIR)/package.mk

ifeq ($(CONFIG_TARGET_ipq),y)
subtarget:=$(SUBTARGET)
else
subtarget:=$(CONFIG_TARGET_BOARD)
endif

ifneq (, $(findstring $(subtarget),"ipq53xx","ipq54xx","ipq52xx"))
NSS_EIP_DIR:=eip196
else ifneq (, $(findstring $(subtarget),"ipq96xx"))
NSS_EIP_DIR:=eip197_v2
else
NSS_EIP_DIR:=eip197
endif

ifeq ($(CONFIG_PACKAGE_kmod-qca-nss-eip-crypto),y)
eip_crypto:=m
endif

define KernelPackage/qca-nss-eip
  SECTION:=kernel
  CATEGORY:=Kernel modules
  SUBMENU:=Network Devices
  DEPENDS:=@TARGET_ipq95xx||TARGET_ipq53xx||TARGET_ipq54xx||TARGET_ipq52xx||TARGET_ipq96xx \
		+TARGET_ipq96xx:qca-nss-fw-eip-ju \
		+TARGET_ipq95xx:kmod-qca-nss-ppe \
                +TARGET_ipq96xx:kmod-qca-nss-ppe
  TITLE:=Kernel driver for NSS EIP driver
  FILES:=$(PKG_BUILD_DIR)/driver/$(NSS_EIP_DIR)/qca-nss-eip.ko
  AUTOLOAD:=$(call AutoLoad,52,qca-nss-eip)
endef

define KernelPackage/qca-nss-eip/Description
This package contains a NSS EIP driver for QCA chipset
endef

define KernelPackage/qca-nss-eip/install
	$(INSTALL_DIR) $(1)/usr/include/qca-nss-eip
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_BIN) ./files/eip_dump.sh $(1)/usr/bin/
	$(CP) $(PKG_BUILD_DIR)/driver/exports/* $(1)/usr/include/qca-nss-eip
endef

define KernelPackage/qca-nss-eip-crypto
  SECTION:=kernel
  CATEGORY:=Kernel modules
  SUBMENU:=Network Devices
  DEPENDS:=@TARGET_ipq95xx||TARGET_ipq_ipq95xx_32||TARGET_ipq53xx||TARGET_ipq54xx||TARGET_ipq52xx||TARGET_ipq96xx \
		+kmod-qca-nss-eip \
		+kmod-crypto-authenc
  TITLE:=Kernel NSS EIP crypto client
  FILES:=$(PKG_BUILD_DIR)/clients/crypto/qca-nss-eip-crypto.ko
endef

define KernelPackage/qca-nss-eip-crypto/Description
This package contains a NSS EIP crypto client for QCA chipset
endef

define Build/InstallDev
	$(INSTALL_DIR) $(1)/usr/include/qca-nss-eip
	$(CP) $(PKG_BUILD_DIR)/clients/exports/* $(1)/usr/include/qca-nss-eip
	$(CP) $(PKG_BUILD_DIR)/driver/exports/* $(1)/usr/include/qca-nss-eip
endef

define KernelPackage/qca-nss-eip-ipsec
  SECTION:=kernel
  CATEGORY:=Kernel modules
  SUBMENU:=Network Devices
  DEPENDS:=@TARGET_ipq95xx||TARGET_ipq53xx||TARGET_ipq54xx||TARGET_ipq52xx||TARGET_ipq96xx \
	  	+kmod-qca-nss-eip \
		kmod-qca-nss-ecm \
		+kmod-qca-nss-ppe-vp +kmod-qca-nss-netfn-pkt-steer
  TITLE:=Kernel IPsec client for NSS EIP driver
  FILES:=$(PKG_BUILD_DIR)/clients/ipsec/qca-nss-eip-ipsec.ko
endef

define KernelPackage/qca-nss-eip-ipsec/Description
This package contains a IPsec offload client for EIP driver.
endef

define KernelPackage/qca-nss-eip-ipsec/install
	$(INSTALL_DIR) $(1)/usr/include/qca-nss-eip
	$(CP) $(PKG_BUILD_DIR)/clients/exports/eip_ipsec.h $(1)/usr/include/qca-nss-eip
	$(INSTALL_DIR) $(1)/etc/init.d
	$(INSTALL_BIN) ./files/qca-nss-ipsec $(1)/etc/init.d/qca-nss-ipsec
endef

EXTRA_CFLAGS+= \
	-I$(STAGING_DIR)/usr/include/qca-nss-eip

EXTRA_CFLAGS+= -I$(STAGING_DIR)/usr/include/qca-nss-ppe

ifneq ($(CONFIG_PACKAGE_kmod-qca-nss-eip-ipsec),)
EXTRA_CFLAGS+= -I$(PKG_BUILD_DIR)/clients/exports
EXTRA_CFLAGS+= -I$(STAGING_DIR)/usr/include/qca-nss-ecm
EXTRA_CFLAGS+= -I$(STAGING_DIR)/usr/include/qca-nss-netfn
MAKE_OPTS+=eip_ipsec=m
endif

define Build/Compile
	$(KERNEL_MAKE) $(strip $(MAKE_OPTS)) \
		CC="$(TARGET_CC)" \
		M="$(PKG_BUILD_DIR)" \
		EXTRA_CFLAGS="$(EXTRA_CFLAGS)" \
		NSS_EIP_DIR=$(NSS_EIP_DIR) \
		eip_crypto=$(eip_crypto) \
		SoC="$(subtarget)" \
		modules
endef

$(eval $(call KernelPackage,qca-nss-eip))
$(eval $(call KernelPackage,qca-nss-eip-crypto))
$(eval $(call KernelPackage,qca-nss-eip-ipsec))
