#!/bin/sh
#
# Copyright (C) 2016 LEDE
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(board_name)

to_hex () {
	input=$1
	hex=$(printf '0x%x' $input)
	echo $hex
}

ubootenv_mtdinfo () {
	UBOOTENV_PART=$(cat /proc/mtd | grep APPSBLENV)
	mtd_dev=$(echo $UBOOTENV_PART | awk '{print $1}' | sed 's/:$//')
	mtd_size=$(echo $UBOOTENV_PART | awk '{print "0x"$2}')
	mtd_erase=$(echo $UBOOTENV_PART | awk '{print "0x"$3}')
	nor_flash=$(find /sys/bus/spi/devices/*/mtd -name ${mtd_dev})

	if [ -z "$UBOOTENV_PART" ]; then
		mtd_dev=$(echo $(find_mmc_part "0:APPSBLENV") | sed 's/^.\{5\}//')
		if [ -n "$mtd_dev" ]; then
			EMMC_UBOOTENV_PART=$(cat /proc/partitions | grep $mtd_dev)
			#convert block to bytes
			emmc_ubootenv_size=`expr $(echo $EMMC_UBOOTENV_PART | awk '{print $3}') \* 1024`
			ubootenv_size=0x`printf "%x" $emmc_ubootenv_size`
		fi
		mtd_erase=""
	elif [ -n "$nor_flash" ]; then
		ubootenv_size=$mtd_size
		sectors=$(( $ubootenv_size / $mtd_erase ))
		sectors=0x`printf "%x" $sectors`
	else
		# size is fixed to 0x40000 in u-boot
		ubootenv_size=0x40000
		sectors=$(( $ubootenv_size / $mtd_erase ))
		sectors=0x`printf "%x" $sectors`
	fi

	echo /dev/$mtd_dev 0x0 $ubootenv_size $mtd_erase $sectors
}
case "$board" in
qcom,ipq5332-ap-*)
	ubootenv_add_uci_config $(ubootenv_mtdinfo)
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
