#!/bin/sh

CFG=/etc/board.json

. /lib/functions/uci-defaults.sh

ipq54xx_setup_interfaces()
{
	local num_iface="$(ls /proc/device-tree/soc*/dp*/name |wc -l)"

	case "$num_iface" in
	6)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4 eth5" "eth0"
		;;
	5)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4" "eth0"
		;;
	3)
		ucidef_set_interfaces_lan_wan "eth1 eth2" "eth0"
		;;
	2)
		ucidef_set_interfaces_lan_wan "eth1" "eth0"
		ucidef_add_switch "switch1"
		ucidef_add_switch_attr "switch1" "enable" false
		;;
	*)
		echo "Unsupported hardware. Network interfaces not intialized"
		;;
	esac
}

board_config_update
ipq54xx_setup_interfaces
board_config_flush

exit 0
