#!/bin/sh

CFG=/etc/board.json

. /lib/functions/uci-defaults.sh

ipq95xx_setup_interfaces()
{
	local board="$1"

	case "$board" in
	qcom,ipq9574-ap-al05 |\
	qcom,ipq9574-ap-al06 |\
	qcom,ipq9574-ap-al02-c4 |\
	qcom,ipq9574-ap-al02-c7)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4 eth5" "eth0"
		;;
	prpl,freedom)
		ucidef_set_interfaces_lan_wan "lan1 lan2 lan3 lan4" "wan"
		;;
	*)
		echo "Unsupported hardware. Network interfaces not intialized"
		;;
	esac
}

board_config_update
board=$(board_name)
ipq95xx_setup_interfaces $board
board_config_flush

exit 0
